name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        run: yarn deploy --token=$1//0eNQnPjjrecIPCgYIARAAGA4SNwF-L9IrDl1JFrAT8U0fWGS2BJP4noqjsDTDBqOYLxBMNt_VfrjFGz8LvkhumlV4HK--qxT0IJA
