name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    environment:
      name: REACT_ENV
    steps:
      - name: Env
        run: echo ${{secrets.REACT_TEST}}
      - name: mkdir
        run: mkdir test
      - name: ls
        run: ls
  test:
    runs-on: macos-latest
    steps:
      - name: ls
        run: ls
  deploy_firebase_hosting:
    runs-on: macos-latest
    environment:
      name: FIREBASE_ENV
    steps:
      - name: Environments
        run: echo ${{secrets.REACT_TEST}}
      # - name: Checkout the repository
      #   uses: actions/checkout@master
      # - name: Install Dependencies
      #   run: yarn install
      #   working-directory: ./client/app
      # - name: Build
      #   run: yarn build
      #   working-directory: ./client/app
      # - name: Deploy to Firebase
      #   run: yarn deploy --token=${{secrets.FIREBASE_TOKEN}}
      #   working-directory: ./client/app
